# Generated by Django 3.0.3 on 2020-02-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('body', models.TextField(db_index=True)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
