# Generated by Django 3.0.3 on 2020-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz', '0002_auto_20200220_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cost',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
