# Generated by Django 3.0.3 on 2020-02-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz', '0003_auto_20200220_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cost',
            field=models.FloatField(db_index=True),
        ),
    ]
