# Generated by Django 3.0.3 on 2020-02-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pzz', '0004_auto_20200220_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
