# Generated by Django 3.0.3 on 2020-02-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pzz', '0007_auto_20200220_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='cost',
            new_name='price',
        ),
    ]
